name: Export Godot Game
on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  export_web:
    runs-on: ubuntu-latest
    name: Export Web Game
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Build Directory
        run: mkdir -p build/web

      - name: Export Game
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: false
          export_preset_name: Web

      - name: Commit Build to Main
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Deploy Build to Main [skip ci]"
          file_pattern: 'build/web/*'
